# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "^v*.*.*$"
      - "^v*.*.*-rc[0-9]$"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: mkdir -p ./bin && go build -x -o ./bin/pg_pro .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: endsWith(github.ref, 'refs/tags/')
        with:
          prerelease: contains(github.ref, 'rc')
          body: |
            ${{ github.event.head_commit.message }}

            Docker Image: ghcr.io/mhkarimi1383/pg_pro:${{ github.event.release.tag_name }}
          files: ./bin/pg_pro
